Practice with 'Text' and 'TextStyle' widgets
arthur-darguzhis/surf-flutter-course-darguzhis pull request #6
Opened 2021-03-23 16:16 UTC by arthur-darguzhis

![image](https://user-images.githubusercontent.com/58817366/112180062-4597bb00-8c0c-11eb-91e4-85a3d5adfdd3.png)

2021-03-24 17:37 UTC, artem-zaitsev requested changes
Лучше сделать сразу и подключить все начертания.

2021-03-24 17:37 UTC, artem-zaitsev commented on lib/ui/screen/sight_list_screen.dart
> +              fontWeight: FontWeight.bold),
В дизайне 700(или normal).
 При этом вы заметили, наверное, что в приложении все таки к4ак в дизайне, а не так как вы указали, здесь.
 Все из-за того, что вы не все шрифты подключили в пабспек и не указали им вес.

2021-03-29 07:55 UTC, arthur-darguzhis commented on lib/ui/screen/sight_list_screen.dart
> +              fontWeight: FontWeight.bold),
Теперь подключил все шрифты и указал вес 700
https://github.com/arthur-darguzhis/surf-flutter-course-darguzhis/pull/6/commits/d431ffe42f9d01fe55b930b66f80fc052a7eab0d
![image](https://user-images.githubusercontent.com/58817366/112804323-f4108580-907c-11eb-8a2e-3b1ee6caa005.png)

2021-03-29 17:59 UTC, artem-zaitsev approved these changes

2021-03-30 15:14 UTC, merged